name: eslint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: eslint
    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
